### ISSUE TITLE
Report missing layers in spritesheet

### ISSUE THREAD

**Issue by ShinyStar** [ClockworkDev/ClockworkVSCodePlugin#4]
It should be reported when you try to run the game when there is a spritesheet that has layers in a state which have not been defined within the <layers> tags.

**Comment by arcadiogarcia** [comment]
Spritesheet.js now reports missing layers in the spritesheet files. https://github.com/ClockworkDev/Spritesheet.js/compare/d6109fdbd84385a5b801ea20f5639b0358afb8b5...6bf7774a7cf4718e9d15c25fe3850e7c3b0712b2#diff-38f9dd8756653d62caa15e19b590f87d
